# Vector Configuration

# Embedding Model Settings
embedder:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"  # Sentence transformer model

# AI Model Settings
ai_model:
  name: "gpt-4o-mini"               # OpenAI model name
  max_tokens: 4000                  # Maximum tokens in AI response
  temperature: 0.1                  # Temperature for AI responses
  provider: "openai"                # AI provider

  # Response length presets
  response_lengths:
    short: 150      # Brief, concise answers
    medium: 500     # Balanced detail level
    long: 1500      # Comprehensive answers

# Vector Database Settings
vector_database:
  # Use cloud Qdrant instance
  url: "https://74f6dd7e-d502-40f1-974b-bd7898518e89.us-east4-0.gcp.cloud.qdrant.io:6333"
  api_key: null                     # Set QDRANT_API_KEY environment variable
  collection_name: "vector_documents"  # Default collection name
  
  # Legacy local storage (deprecated)
  local_path: "./qdrant_db"         # Path for local file storage
