# Vector Configuration

# Embedding Model Settings
embedder:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"  # Sentence transformer model

# AI Model Settings - Multiple Models Support
ai_models:
  # Search model - optimized for generating search terms
  search:
    name: "gpt-5-nano"              # Model name
    max_tokens: 4000                # Lower token limit for search queries
    temperature: 1                  # Lower temperature for more focused results
    provider: "openai"              # AI provider (openai, anthropic, google, etc.)
  
  # Answer model - optimized for comprehensive responses
  answer:
    name: "gpt-5"                   # Model name
    max_tokens: 15000               # Higher token limit for detailed responses
    temperature: 1                  # Temperature for AI responses
    provider: "openai"              # AI provider

# Response length presets
response_lengths:
  short: 4000      # Brief, concise answers
  medium: 8000     # Balanced detail level
  long: 15000      # Comprehensive answers

# Chat Configuration
chat:
  max_history_messages: 40          # Maximum messages to keep in session
  summary_trigger_messages: 14      # Trigger summarization after this many messages
  max_context_results: 40           # Maximum search results to use for context
  default_top_k: 12                 # Default number of search results per chat turn

# Vector Database Settings
vector_database:

  # Use cloud Qdrant instance
  url: null                         # Set QDRANT_URL environment variable or set to null for local
  api_key: null                     # Set QDRANT_API_KEY environment variable
  
  # Local Storage
  local_path: "./qdrant_db"         # Path for local file storage

 # Directory to store generated artifacts

# Storage Configuration
storage:
  converted_documents_dir: "./data/converted_documents"               
  registry_dir: "./vector_registry"            

  
  # PostgreSQL configuration (when using postgresql backend - future)
  # postgres_connection_string: "postgresql://user:password@localhost/vectordb"