Zoning_and_Land_Use_Regulations:
  - Permitted and prohibited land uses
  - Minimum front, side, and rear setbacks
  - Overlay districts and special zoning areas
  - Environmental protection districts:
      - Groundwater recharge areas
      - Stream corridor buffers
      - Wetlands protection zones

Site_Planning_and_Design_Standards:
  General_Site_Features:
    - Dumpsters and refuse enclosures
    - Vehicular and pedestrian access
    - Gates and security controls
    - Perimeter fencing and walls
    - Screening of mechanical or service areas
    - Landscape buffers between land uses
  Landscaping:
    - Tree protection and preservation requirements
    - Minimum planting requirements and species guidelines
  Parking_and_Circulation:
    - Minimum and maximum off-street parking requirements
    - Stall dimensions for standard, compact, and accessible spaces
    - Drive aisles, queuing lanes, and drive-through circulation
    - Interior and terminal landscape islands
    - Signage, striping, ADA access, pedestrian routes, and crosswalks
    - Fire apparatus access, surface materials, grading, curb cuts & gutters

Transportation_and_Roadway_Design:
  Road_Geometry_and_Design:
    - Maximum grades
    - Minimum vertical and horizontal curve radii
    - Intersection layout and sight triangle requirements
  Street_Classifications:
    - Public streets
    - Private streets
    - Cul-de-sacs and turnaround standards
  Design_Elements_and_Improvements:
    - Right-of-way widths
    - Pavement widths, radii, and jog alignment
    - Pavement design and construction specifications
    - Curb and gutter standards
    - Auxiliary lanes: deceleration, left-turn, and merge lanes
    - Roadway signage, pavement markings, and traffic control devices
    - Minimum sight distance and clear zone requirements
    - Utility placement within ROW
    - Pedestrian crosswalks and curb ramps

Stormwater_and_Environmental_Protection:
  Natural_Features_and_Hazard_Areas:
    - Creek setbacks and stream buffer zones
    - FEMA flood hazard areas and floodplain regulations
    - Minimum Finish Floor Elevation (FFE) above base flood
  Stormwater_Infrastructure:
    - Detention, retention, and infiltration facilities
    - Culverts, ditches, and open channels
    - Stormwater easements and access provisions
    - Impoundments and wet/dry ponds
    - Erosion and sediment control during construction

Utility_Services:
  - Availability and connection to public water and sanitary sewer
  - Extension of utilities to serve the site
  - Fire hydrant spacing and fire flow requirements
  - Coordination and spacing of utility lines and crossings

Permitting_Submittals_and_Technical_Reports:
  Development_Review_Process:
    - Pre-application consultation requirements
    - Submittal checklists and application procedures
    - Pre-submittal and pre-construction meetings
  Required_Plans_and_Documents:
    - Concept Plan
    - Site Development Plan
    - Grading and Drainage Plan
    - Utility Plan
    - Construction Plans and Specifications
    - Record Drawings / As-Builts
    - Preliminary and Final Plats
  Required_Technical_Analysis:
    - Traffic Impact Study (TIS)
    - Hydrologic and hydraulic (H&H) analysis
    - Stormwater Management Concept Plan
  Additional_Documentation:
    - Letters of availability (water/sewer)
    - Environmental impact reports (if applicable)
    - Developer agreements or fee-in-lieu programs
